# Heat Map data source
# Note: Heat Maps are read-only and automatically generated by Azure Traffic Manager
# This data source retrieves heat map data for analysis

data "azapi_resource" "this" {
  type      = "Microsoft.Network/trafficManagerProfiles/heatMaps@2022-04-01"
  parent_id = var.traffic_manager_profile_id
  name      = "default" # Heat maps always use the name "default"
}
